--Task 1
--Step 1
ALTER TABLE PRODUCTLIST
ADD COLUMN PRICE DECIMAL(10, 2),
ADD COLUMN DESCRIPTION VARCHAR(255);

--Step 2
UPDATE PRODUCTLIST p
JOIN STOREFRONT s ON p.ProductID = s.ProductID
SET p.PRICE = s.PRICE,
    p.DESCRIPTION = s.DESCRIPTION;

--Step 3
DROP TABLE STOREFRONT;

--Task 2
--Step 1
CREATE TABLE CHATLOG (
    CHATID NUMBER(3),
    RECEIVERID NUMBER(3),
    SENDERID NUMBER(3),
    DATESENT DATE,
    CONTENT VARCHAR2(250),
    CONSTRAINT PK_CHATLOG PRIMARY KEY (CHATID),
    CONSTRAINT FK_CHATLOG_RECEIVERID FOREIGN KEY (RECEIVERID) REFERENCES USERBASE(USERID),
    CONSTRAINT FK_CHATLOG_SENDERID FOREIGN KEY (SENDERID) REFERENCES USERBASE(USERID)
);
--Step 2
INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT) VALUES (1, 101, 102, TO_DATE('2026-02-01', 'YYYY-MM-DD'), 'Hey, did you see the new game update?');
INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT) VALUES (2, 102, 101, TO_DATE('2026-02-01', 'YYYY-MM-DD'), 'Not yet, downloading it now!');
INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT) VALUES (3, 103, 104, TO_DATE('2026-02-02', 'YYYY-MM-DD'), 'Can you help me with Level 5?');
INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT) VALUES (4, 104, 103, TO_DATE('2026-02-02', 'YYYY-MM-DD'), 'Sure! Meet me at the north gate.');
INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT) VALUES (5, 105, 106, TO_DATE('2026-02-03', 'YYYY-MM-DD'), 'Great match earlier!');
INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT) VALUES (6, 106, 105, TO_DATE('2026-02-03', 'YYYY-MM-DD'), 'Thanks! You too. GG.');
INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT) VALUES (7, 101, 103, TO_DATE('2026-02-03', 'YYYY-MM-DD'), 'Are we still playing tonight?');
INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT) VALUES (8, 103, 101, TO_DATE('2026-02-03', 'YYYY-MM-DD'), 'Yeah, logging on in 10 minutes.');
INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT) VALUES (9, 107, 108, TO_DATE('2026-02-03', 'YYYY-MM-DD'), 'Check out this screenshot!');
INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT) VALUES (10, 108, 107, TO_DATE('2026-02-03', 'YYYY-MM-DD'), 'Whoa, that looks amazing.');

--Task 3
--Step 1
CREATE TABLE FRIENDSLIST (
    USERID NUMBER(3),
    FRIENDID NUMBER(3),
    CONSTRAINT PK_FRIENDSLIST PRIMARY KEY (USERID, FRIENDID),
    CONSTRAINT FK_FRIENDSLIST_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID),
    CONSTRAINT FK_FRIENDSLIST_FRIENDID FOREIGN KEY (FRIENDID) REFERENCES USERBASE(USERID)
);
--Step 2
INSERT ALL 
  INTO FRIENDSLIST (USERID, FRIENDID) VALUES (101, 102)
  INTO FRIENDSLIST (USERID, FRIENDID) VALUES (102, 101)
  INTO FRIENDSLIST (USERID, FRIENDID) VALUES (101, 103)
  INTO FRIENDSLIST (USERID, FRIENDID) VALUES (103, 101)
  INTO FRIENDSLIST (USERID, FRIENDID) VALUES (104, 105)
  INTO FRIENDSLIST (USERID, FRIENDID) VALUES (105, 104)
  INTO FRIENDSLIST (USERID, FRIENDID) VALUES (106, 101)
  INTO FRIENDSLIST (USERID, FRIENDID) VALUES (107, 108)
  INTO FRIENDSLIST (USERID, FRIENDID) VALUES (108, 107)
  INTO FRIENDSLIST (USERID, FRIENDID) VALUES (109, 110)
SELECT * FROM dual;

--Task 4
--Step 1
CREATE TABLE WISHLIST (
    USERID NUMBER(3),
    PRODUCTCODE VARCHAR2(5),
    POSITION NUMBER(3),
    CONSTRAINT PK_WISHLIST PRIMARY KEY (USERID, PRODUCTCODE),
    CONSTRAINT FK_WISHLIST_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID),
    CONSTRAINT FK_WISHLIST_PRODUCTCODE FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCTLIST(PRODUCTCODE)
);

--Step 2
INSERT ALL
    INTO WISHLIST (USERID, PRODUCTCODE, POSITION) VALUES (101, 'GAME1', 1)
    INTO WISHLIST (USERID, PRODUCTCODE, POSITION) VALUES (101, 'GAME5', 2)
    INTO WISHLIST (USERID, PRODUCTCODE, POSITION) VALUES (102, 'GAME2', 1)
    INTO WISHLIST (USERID, PRODUCTCODE, POSITION) VALUES (103, 'GAME1', 1)
    INTO WISHLIST (USERID, PRODUCTCODE, POSITION) VALUES (104, 'GAME9', 1)
    INTO WISHLIST (USERID, PRODUCTCODE, POSITION) VALUES (105, 'GAME3', 1)
    INTO WISHLIST (USERID, PRODUCTCODE, POSITION) VALUES (106, 'GAME1', 1)
    INTO WISHLIST (USERID, PRODUCTCODE, POSITION) VALUES (107, 'GAME4', 1)
    INTO WISHLIST (USERID, PRODUCTCODE, POSITION) VALUES (108, 'GAME2', 1)
    INTO WISHLIST (USERID, PRODUCTCODE, POSITION) VALUES (109, 'GME12', 1)
SELECT * FROM dual;

--Task 5
--Step 1
CREATE TABLE USERPROFILE (
    USERID NUMBER(3),
    IMAGEFILE VARCHAR2(250),
    DESCRIPTION VARCHAR2(250),
    CONSTRAINT PK_USERPROFILE PRIMARY KEY (USERID),
    CONSTRAINT FK_USERPROFILE_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID)
);

--Step 2
INSERT ALL
    INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION) VALUES (101, 'img_101.jpg', 'Lover of RPGs and fantasy.')
    INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION) VALUES (102, 'img_102.png', 'Competitive FPS player.')
    INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION) VALUES (103, 'default.jpg', 'Casual gamer looking for friends.')
    INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION) VALUES (104, 'avatar.jpg', 'Speedrunner in training.')
    INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION) VALUES (105, 'pic.jpg', 'Strategy game enthusiast.')
    INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION) VALUES (106, 'me.png', 'I only play indie games.')
    INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION) VALUES (107, 'profile.jpg', 'Collects retro consoles.')
    INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION) VALUES (108, 'user8.jpg', 'Streaming nightly!')
    INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION) VALUES (109, 'cat.jpg', 'Keyboard and mouse purist.')
    INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION) VALUES (110, 'pro.jpg', 'VaporGames beta tester.')
SELECT * FROM dual;

--Task 6
--Step 1
-- Task 6: Create SECURITYQUESTION table and insert data
CREATE TABLE SECURITYQUESTION (
    QUESTIONID NUMBER,
    USERID NUMBER(3),
    QUESTION VARCHAR2(250),
    ANSWER VARCHAR2(250),
    CONSTRAINT PK_SECURITYQUESTION PRIMARY KEY (QUESTIONID),
    CONSTRAINT FK_SECURITYQUESTION_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID)
);
--Step 2
INSERT ALL
    INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER) VALUES (1, 101, 'First pet name?', 'Nala')
    INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER) VALUES (2, 102, 'First pet name?', 'Rover')
    INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER) VALUES (3, 103, 'City of birth?', 'Fairfax')
    INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER) VALUES (4, 104, 'Favorite color?', 'Blue')
    INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER) VALUES (5, 105, 'High school name?', 'Oakton')
    INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER) VALUES (6, 106, 'Mother maiden name?', 'Smith')
    INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER) VALUES (7, 107, 'First car?', 'Civic')
    INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER) VALUES (8, 108, 'Favorite food?', 'Pizza')
    INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER) VALUES (9, 109, 'City of birth?', 'Manassas')
    INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER) VALUES (10, 110, 'First pet name?', 'Goldie')
SELECT * FROM dual;

--Task 7
--Step 1
CREATE TABLE COMMUNITYRULES (
    RULENUM NUMBER(3),
    TITLE VARCHAR2(250),
    DESCRIPTION VARCHAR2(250),
    SEVERITYPOINT NUMBER(4),
    CONSTRAINT PK_COMMUNITYRULES PRIMARY KEY (RULENUM)
);
--Step 2
INSERT ALL
    INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT) VALUES (1, 'Respect', 'No harassment or bullying.', 100)
    INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT) VALUES (2, 'Cheating', 'No use of third-party exploits.', 500)
    INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT) VALUES (3, 'Spam', 'No commercial advertising in chat.', 50)
    INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT) VALUES (4, 'Privacy', 'Do not share personal info of others.', 300)
    INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT) VALUES (5, 'Impersonation', 'Do not pretend to be staff.', 400)
    INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT) VALUES (6, 'Language', 'No excessive profanity.', 25)
    INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT) VALUES (7, 'Trading', 'No real-money trading for items.', 200)
    INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT) VALUES (8, 'Griefing', 'No intentional ruining of gameplay.', 150)
    INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT) VALUES (9, 'NSFW Content', 'No inappropriate imagery.', 350)
    INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT) VALUES (10, 'Threats', 'No threats of physical harm.', 1000)
SELECT * FROM dual;

--Task 8
--Step 1
-- Task 8: Create INFRACTIONS table and insert data
CREATE TABLE INFRACTIONS (
    INFRACTIONID NUMBER,
    USERID NUMBER(3),
    RULENUM NUMBER(3),
    DATEASSIGNED DATE,
    PENALTY VARCHAR2(250),
    CONSTRAINT PK_INFRACTIONS PRIMARY KEY (INFRACTIONID),
    CONSTRAINT FK_INFRACTIONS_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID),
    CONSTRAINT FK_INFRACTIONS_RULENUM FOREIGN KEY (RULENUM) REFERENCES COMMUNITYRULES(RULENUM)
);
--Step 2
INSERT ALL
    INTO INFRACTIONS (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY) VALUES (1, 102, 2, TO_DATE('2026-01-05', 'YYYY-MM-DD'), '7 Day Ban')
    INTO INFRACTIONS (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY) VALUES (2, 105, 3, TO_DATE('2026-01-10', 'YYYY-MM-DD'), 'Warning')
    INTO INFRACTIONS (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY) VALUES (3, 108, 6, TO_DATE('2026-01-12', 'YYYY-MM-DD'), 'Muted for 24h')
    INTO INFRACTIONS (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY) VALUES (4, 101, 1, TO_DATE('2026-01-15', 'YYYY-MM-DD'), 'Warning')
    INTO INFRACTIONS (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY) VALUES (5, 103, 8, TO_DATE('2026-01-20', 'YYYY-MM-DD'), '3 Day Ban')
    INTO INFRACTIONS (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY) VALUES (6, 109, 2, TO_DATE('2026-01-22', 'YYYY-MM-DD'), 'Permanent Ban')
    INTO INFRACTIONS (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY) VALUES (7, 104, 3, TO_DATE('2026-01-25', 'YYYY-MM-DD'), 'Warning')
    INTO INFRACTIONS (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY) VALUES (8, 110, 5, TO_DATE('2026-01-28', 'YYYY-MM-DD'), '30 Day Ban')
    INTO INFRACTIONS (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY) VALUES (9, 106, 6, TO_DATE('2026-02-01', 'YYYY-MM-DD'), 'Muted for 48h')
    INTO INFRACTIONS (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY) VALUES (10, 107, 1, TO_DATE('2026-02-03', 'YYYY-MM-DD'), 'Warning')
SELECT * FROM dual;

--Task 9
--Step 1
CREATE TABLE USERSUPPORT (
    TICKETID NUMBER,
    EMAIL VARCHAR2(250),
    ISSUE VARCHAR2(250),
    DATESUBMITTED DATE,
    DATEUPDATED DATE,
    STATUS VARCHAR2(250),
    CONSTRAINT PK_USERSUPPORT PRIMARY KEY (TICKETID)
);
--Step 2
INSERT ALL
    INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS) VALUES (1, 'user101@email.com', 'Cannot login', TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-01-02', 'YYYY-MM-DD'), 'CLOSED')
    INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS) VALUES (2, 'user102@email.com', 'Missing item', TO_DATE('2026-02-01', 'YYYY-MM-DD'), TO_DATE('2026-02-02', 'YYYY-MM-DD'), 'IN PROGRESS')
    INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS) VALUES (3, 'user105@email.com', 'Bug in Level 2', TO_DATE('2026-02-03', 'YYYY-MM-DD'), TO_DATE('2026-02-03', 'YYYY-MM-DD'), 'NEW')
    INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS) VALUES (4, 'user108@email.com', 'Payment failed', TO_DATE('2026-02-04', 'YYYY-MM-DD'), TO_DATE('2026-02-04', 'YYYY-MM-DD'), 'NEW')
    INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS) VALUES (5, 'user103@email.com', 'Account stolen', TO_DATE('2025-12-20', 'YYYY-MM-DD'), TO_DATE('2025-12-25', 'YYYY-MM-DD'), 'CLOSED')
    INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS) VALUES (6, 'user110@email.com', 'Connection lag', TO_DATE('2026-02-01', 'YYYY-MM-DD'), TO_DATE('2026-02-03', 'YYYY-MM-DD'), 'IN PROGRESS')
    INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS) VALUES (7, 'user104@email.com', 'Feedback', TO_DATE('2026-01-15', 'YYYY-MM-DD'), TO_DATE('2026-01-15', 'YYYY-MM-DD'), 'CLOSED')
    INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS) VALUES (8, 'user107@email.com', 'Harassment report', TO_DATE('2026-02-05', 'YYYY-MM-DD'), TO_DATE('2026-02-05', 'YYYY-MM-DD'), 'NEW')
    INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS) VALUES (9, 'user106@email.com', 'Update stuck', TO_DATE('2026-01-30', 'YYYY-MM-DD'), TO_DATE('2026-02-01', 'YYYY-MM-DD'), 'IN PROGRESS')
    INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS) VALUES (10, 'user109@email.com', 'Password reset', TO_DATE('2026-02-04', 'YYYY-MM-DD'), TO_DATE('2026-02-04', 'YYYY-MM-DD'), 'NEW')
SELECT * FROM dual;

--Task 10
--Step 1
CREATE VIEW UNIQUE_SECURITY_QUESTIONS AS
SELECT DISTINCT QUESTION
FROM SECURITYQUESTION;

--Step 2
CREATE VIEW ACTIVE_SUPPORT_TICKETS AS
SELECT TICKETID, EMAIL, ISSUE, DATEUPDATED
FROM USERSUPPORT
WHERE STATUS IN ('NEW', 'IN PROGRESS')
ORDER BY DATEUPDATED ASC;