-- 1.
SELECT u.USERNAME, MIN(r.RATING) AS LOWEST_RATING
FROM USERBASE u
JOIN REVIEWS r ON u.USERID = r.USERID
GROUP BY u.USERNAME;

-- 2.
SELECT u.EMAIL, s.QUESTION, s.ANSWER
FROM USERBASE u
JOIN SECURITYQUESTION s ON u.USERID = s.USERID;

-- 3.
SELECT FIRSTNAME, EMAIL, WALLETFUNDS
FROM USERBASE
WHERE USERID NOT IN (SELECT USERID FROM WISHLIST);

-- 4.
SELECT u.USERNAME, COUNT(o.PRODUCTCODE) AS PRODUCT_COUNT
FROM USERBASE u
JOIN ORDERS o ON u.USERID = o.USERID
GROUP BY u.USERNAME;

-- 5.
SELECT DISTINCT u.USERNAME, FLOOR(MONTHS_BETWEEN(SYSDATE, u.BIRTHDAY) / 12) AS AGE
FROM USERBASE u
JOIN ORDERS o ON u.USERID = o.USERID
WHERE MONTHS_BETWEEN(SYSDATE, o.PURCHASEDATE) <= 6;

-- 6.
SELECT u.USERNAME, u.BIRTHDAY
FROM USERBASE u
JOIN FRIENDSLIST f ON u.USERID = f.USERID
GROUP BY u.USERNAME, u.BIRTHDAY
ORDER BY COUNT(f.FRIENDID) DESC
FETCH FIRST 1 ROWS ONLY;

-- 7.
SELECT DISTINCT p.PRODUCTNAME, p.RELEASEDATE, p.PRICE, p.DESCRIPTION
FROM PRODUCTLIST p
JOIN WISHLIST w ON p.PRODUCTCODE = w.PRODUCTCODE;

-- 8.
SELECT p.PRODUCTNAME, MAX(r.RATING) AS HIGHEST_RATING, COUNT(r.REVIEW) AS REVIEW_COUNT
FROM PRODUCTLIST p
JOIN REVIEWS r ON p.PRODUCTCODE = r.PRODUCTCODE
GROUP BY p.PRODUCTNAME
ORDER BY HIGHEST_RATING DESC;

-- 9.
CREATE VIEW EXTREME_RATED_PRODUCTS AS
SELECT p.PRODUCTNAME, p.GENRE, r.RATING
FROM PRODUCTLIST p
JOIN REVIEWS r ON p.PRODUCTCODE = r.PRODUCTCODE
WHERE r.RATING IN (1, 5)
ORDER BY r.RATING ASC;

-- 10.
SELECT p.GENRE, COUNT(o.ORDERID) AS ORDER_COUNT
FROM PRODUCTLIST p
JOIN ORDERS o ON p.PRODUCTCODE = o.PRODUCTCODE
GROUP BY p.GENRE
ORDER BY p.GENRE ASC;

-- 11.
CREATE VIEW PUBLISHER_STATS AS
SELECT p.PUBLISHER, AVG(p.PRICE) AS AVG_PRICE, SUM(u.HOURSPLAYED) AS TOTAL_HOURS
FROM PRODUCTLIST p
JOIN USERLIBRARY u ON p.PRODUCTCODE = u.PRODUCTCODE
GROUP BY p.PUBLISHER;

-- 12.
SELECT p.PUBLISHER, SUM(o.PRICE) AS TOTAL_SPENT
FROM ORDERS o
JOIN PRODUCTLIST p ON o.PRODUCTCODE = p.PRODUCTCODE
GROUP BY p.PUBLISHER
ORDER BY TOTAL_SPENT DESC;

-- 13.
SELECT s.TICKETID, u.USERNAME, s.EMAIL, s.ISSUE
FROM USERSUPPORT s
LEFT JOIN USERBASE u ON s.EMAIL = u.EMAIL
WHERE s.STATUS IN ('NEW', 'IN PROGRESS')
ORDER BY s.DATEUPDATED DESC;

-- 14.
SELECT u.USERNAME, COUNT(s.TICKETID) AS TICKET_COUNT
FROM USERBASE u
JOIN USERSUPPORT s ON u.EMAIL = s.EMAIL
GROUP BY u.USERNAME;

-- 15.
SELECT u.USERID, s.EMAIL
FROM USERBASE u
JOIN USERSUPPORT s ON u.EMAIL = s.EMAIL
WHERE LOWER(s.EMAIL) LIKE '%' || LOWER(u.FIRSTNAME) || '%'
   OR LOWER(s.EMAIL) LIKE '%' || LOWER(u.LASTNAME) || '%';

-- 16.
SELECT EMAIL
FROM USERSUPPORT
WHERE STATUS IN ('NEW', 'IN PROGRESS')
  AND EMAIL NOT IN (SELECT EMAIL FROM USERBASE WHERE EMAIL IS NOT NULL);

-- 17.
SELECT s.TICKETID, u.FIRSTNAME, u.LASTNAME, u.USERNAME
FROM USERSUPPORT s
JOIN USERBASE u ON LOWER(s.ISSUE) LIKE '%' || LOWER(u.USERNAME) || '%';

-- 18.
SELECT u.USERNAME, u.PASSWORD
FROM USERBASE u
JOIN USERSUPPORT s ON u.EMAIL = s.EMAIL;

-- 19.
CREATE VIEW RECENT_PENALTIES_USER AS
SELECT u.USERNAME, i.DATEASSIGNED, i.PENALTY
FROM USERBASE u
JOIN INFRACTIONS i ON u.USERID = i.USERID
WHERE i.PENALTY IS NOT NULL 
  AND MONTHS_BETWEEN(SYSDATE, i.DATEASSIGNED) <= 1;

-- 20.
SELECT USERNAME, EMAIL
FROM USERBASE
WHERE MONTHS_BETWEEN(SYSDATE, BIRTHDAY) / 12 >= 18
  AND USERID NOT IN (
      SELECT USERID 
      FROM INFRACTIONS 
      WHERE MONTHS_BETWEEN(SYSDATE, DATEASSIGNED) <= 4
  );

-- 21.
SELECT u.USERNAME, i.DATEASSIGNED, c.RULENUM || ' ' || c.TITLE AS GUIDELINE_NAME
FROM USERBASE u
JOIN INFRACTIONS i ON u.USERID = i.USERID
JOIN COMMUNITYRULES c ON i.RULENUM = c.RULENUM;

-- 22.
SELECT u.USERID, u.USERNAME, u.EMAIL, SUM(c.SEVERITYPOINT) AS TOTAL_SEVERITY_POINTS
FROM USERBASE u
JOIN INFRACTIONS i ON u.USERID = i.USERID
JOIN COMMUNITYRULES c ON i.RULENUM = c.RULENUM
GROUP BY u.USERID, u.USERNAME, u.EMAIL;

-- 23.
SELECT c.TITLE, c.DESCRIPTION, i.PENALTY
FROM INFRACTIONS i
JOIN COMMUNITYRULES c ON i.RULENUM = c.RULENUM;

-- 24.
SELECT u.USERNAME, COUNT(i.INFRACTIONID) AS INFRACTION_COUNT
FROM USERBASE u
JOIN INFRACTIONS i ON u.USERID = i.USERID
GROUP BY u.USERNAME
HAVING COUNT(i.INFRACTIONID) >= 15;