-- Joseph Nettleton

SELECT USERID FROM USERBASE
MINUS
SELECT USERID FROM ORDERS;

SELECT PRODUCTCODE FROM PRODUCTLIST
MINUS
SELECT PRODUCTCODE FROM REVIEWS;

SELECT u.*, 
       CASE WHEN AGE >= 18 THEN 'Adult' ELSE 'Minor' END AS AGE_GROUP 
FROM USERBASE u;

SELECT p.*, 
       CASE WHEN PRICE <= 20.00 THEN 'On Sale' ELSE 'Base Price' END AS PRICE_CATEGORY 
FROM PRODUCTLIST p;

SELECT USERID FROM USERLIBRARY WHERE PRODUCTCODE = 'GAME6'
INTERSECT
SELECT USERID FROM USERPROFILE WHERE IMAGE_URL IS NOT NULL;

SELECT PRODUCTCODE FROM WISHLIST WHERE POSITION IN (1, 2)
INTERSECT
SELECT PRODUCTCODE FROM REVIEWS WHERE RATING >= 3;

SELECT A.USERNAME, A.BIRTHDAY 
FROM USERBASE A 
JOIN USERBASE B ON A.BIRTHDAY = B.BIRTHDAY AND A.USERID != B.USERID;

SELECT * FROM USERLIBRARY 
CROSS JOIN WISHLIST;

SELECT TO_CHAR(USERID) AS ID_CODE, USERNAME AS NAME_DESC FROM USERBASE
UNION ALL
SELECT PRODUCTCODE, PRODUCTNAME FROM PRODUCTLIST;

SELECT TO_CHAR(USERID) AS ID, CHAT_MESSAGE AS ACTIVITY_DATA FROM CHATLOG
UNION ALL
SELECT TO_CHAR(USERID), PROFILE_DESC FROM USERPROFILE;

SELECT USERNAME FROM USERBASE
MINUS
SELECT u.USERNAME FROM USERBASE u JOIN INFRACTIONS i ON u.USERID = i.USERID;

SELECT TITLE, DESCRIPTION FROM COMMUNITYRULES
MINUS
SELECT c.TITLE, c.DESCRIPTION FROM COMMUNITYRULES c JOIN INFRACTIONS i ON c.RULEID = i.RULEID;

SELECT DISTINCT u.USERNAME, u.EMAIL 
FROM USERBASE u 
JOIN INFRACTIONS i ON u.USERID = i.USERID 
WHERE i.PENALTY IS NOT NULL;

SELECT TRUNC(INFRACTION_DATE) AS EVENT_DATE FROM INFRACTIONS
INTERSECT
SELECT TRUNC(SUBMISSION_DATE) FROM USERSUPPORT;

SELECT TITLE, PENALTY 
FROM COMMUNITYRULES;

SELECT c.*, 
       CASE WHEN SEVERITYPOINT >= 10 THEN 'Bannable' ELSE 'Appealable' END AS RULE_STATUS 
FROM COMMUNITYRULES c;

SELECT u.*, 
       CASE WHEN STATUS != 'CLOSED' AND DATEUPDATED < SYSDATE - 7 THEN 'High Priority' ELSE 'Standard' END AS PRIORITY_STATUS 
FROM USERSUPPORT u;

SELECT * FROM USERSUPPORT 
CROSS JOIN INFRACTIONS;

SELECT A.TICKETID AS TICKET_1, B.TICKETID AS TICKET_2, A.DATEUPDATED 
FROM USERSUPPORT A 
JOIN USERSUPPORT B ON TRUNC(A.DATEUPDATED) = TRUNC(B.DATEUPDATED) AND A.TICKETID < B.TICKETID 
WHERE A.STATUS = 'CLOSED' AND B.STATUS = 'CLOSED';

SELECT USERID, 'Account Created' AS ACTIVITY_TYPE FROM USERBASE
UNION ALL
SELECT USERID, 'Infraction Received' FROM INFRACTIONS;